### ISSUE TITLE
Artist Info

### ISSUE THREAD

**Issue by david-simons** [kmrn/spincord#14]
**Relevant or proposed chat command**
1) `!artist <Artist name, e.g. "Michael Jackson">`
2) `!artistart <Artist name>`
3) `!artisturl <Artist name> <optional substring, e.g. "facebook">`

**Is your feature request related to a problem? Please describe.**
Would like to get a summary of artist info from discord chat

**Describe the solution you'd like**
1) returns the first hit of `https://www.discogs.com/search/?type=artist&q=<Artist name>` - with for example the following - maybe not the Sites yet.

![image](https://user-images.githubusercontent.com/6153327/134719928-fb3b0668-ef20-431f-a618-5fca5cf85418.png)

2) return the first hit of the Artist's cover image, only (similar to !albumart)

3) return the urls of the Artists sites, filtered to the one that includes the optional substring

**Comment by kmrn** [comment]
Some better artist support would definitely be nice. Sorry for not seeing this sooner! Haven't checked the repo in a while

**Comment by kmrn** [comment]
@david-simons I just merged a PR adding artist info. Apologies for the crazy long wait. Super cool to see people using this!! Thanks a ton.

**Comment by david-simons** [comment]
> @david-simons I just merged a PR adding artist info. Apologies for the crazy long wait. Super cool to see people using this!! Thanks a ton.

Thank _you_ for adding ` artist` functionality


![image](https://user-images.githubusercontent.com/6153327/154795432-d0d0d4a4-a666-41a4-b86d-71ce949193e9.png)
